version: '2'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comics_development
    ports: # This is only for development. DO NOT expose postgresql ports in a real Dockerfile.
      - "5432:5432"

  web:
    build: .
    environment:
      RAILS_ENV: development
      COMICS_DB_HOST: db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
