version: '2'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comics_development

  web:
    build: .
    command: sh -c "rm -f /app/tmp/pids/server.pid ; bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
