version: '2'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comics_development
    ports: # This is only for development. DO NOT expose postgresql ports in a real Dockerfile.
      - "5432:5432"

  web:
    build: .
    command: sh -c "rm -f /app/tmp/pids/server.pid ; bin/rails server -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@localhost/comics_development"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
