# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ac9bb24aef932127caf913f83c7b909efedef94d610f2f7e374250ba56c8d297a6aafceb8f4a7f5413a6aafb8d0c61070c307e231830eb1c6dff4db0a6853aa

test:
  secret_key_base: 20c8a3e9407788676fa286b8905fe31f740034226b415ffd85bd858f48e9e9d8e54bee0d7ea95758c99c4b6574700ffa31e47acbfd0184ea3dc72abab9bbb669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
